name: Solidity unit test

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Install node modules
        run: npm i
      - name: Unit test solidity
        run: npx hardhat test
